rootProject.name = "reactive-spring-cloud"
include("stream-model")
include("grade-multiplier-producer")
include("grade-multiplier-consumer")
include("avro-schema")
include("student-producer")
include("student-processor")
include("twitter-adapter")
include("tweet-processor")
include("twitter-rest")
