server:
  port: 0

spring:
  application:
    name: grade-multiplier-consumer
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      function:
        definition: consumeGradeMultiplier|consumeGradeValue;gradeDlq
        bindings:
          consumeGradeMultiplier|consumeGradeValue-in-0: composedInput
      default-binder: kafka
      kafka:
        binder:
          auto-create-topics: true
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            spring.json.trusted.packages: "*"
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bindings:
        composedInput:
          destination: grade-topic
          group: grade-consumer
          consumer:
            useNativeDecoding: true
        gradeDlq-out-0:
          destination: grade-error-topic
          producer:
            useNativeEncoding: true